name: GitHub-Profile-3D-Update

on:
  push:
    branches:
      - main
  schedule: 
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Github Actions" 
          author_email: "actions@github.com"
          message: "Update Profile Summary"
          add: "."
          push: "https://github.com/NiREvil5thacc/NiREvil5thacc.git"
